name: BMOsCasino
version: '1.0-SNAPSHOT'
main: me.bmo84.bMOsCasino.BMOsCasino
api-version: '1.20'
authors: [ AcidSenpai ]
description: Mon premier plugins de test
website: www.google.com
commands:
  givemoney:
    description: Give 1000 to player
    usage: /<command>
