name: BMOsCasino
version: '1.0-SNAPSHOT'
main: me.bmo84.bMOsCasino.BMOsCasino
api-version: '1.20'
authors: [ AcidSenpai ]
description: Mon premier plugins de test
website: www.google.com
permissions:
  bmoscasino.create.casino:
    description: Permet aux joueurs de créer un casino
    default: op
